variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DEBIAN_IMAGE: registry.gitlab.com/kyber-labs/kyber-streamer/docker-images/debian-bullseye:20230623133751
  WIN64_IMAGE: registry.gitlab.com/kyber-labs/kyber-streamer/docker-images/debian-win64:20230623134530
  MACOS_RUST_VERSION: 1.70.0

stages:
  - lint
  - build
  - test
  - misc

.variables-windows-x86_64: &variables-windows-x86_64
  CARGO_BUILD_TARGET: x86_64-pc-windows-gnu

.variables-macos-x86_64: &variables-macos-x86_64
  CARGO_BUILD_TARGET: x86_64-apple-darwin

.variables-macos-arm64: &variables-macos-arm64
  CARGO_BUILD_TARGET: aarch64-apple-darwin

lint:
  stage: lint
  image: $DEBIAN_IMAGE
  tags:
    - docker
  only:
    - main
    - merge_requests
    - tags
  script:
    - cargo fmt -- --check
  cache: []

build-debian-buster-x86_64:
  stage: build
  image: $DEBIAN_IMAGE
  tags:
    - docker
  only:
    - main
    - merge_requests
    - tags
  script: |
    cargo build

test-debian-buster-x86_64:
  stage: test
  image: $DEBIAN_IMAGE
  tags:
    - docker
  only:
    - main
    - merge_requests
    - tags
  needs:
    - build-debian-buster-x86_64
  script: |
    cargo test

clippy-debian-buster-x86_64:
  stage: misc
  image: $DEBIAN_IMAGE
  tags:
    - docker
  only:
    - main
    - merge_requests
    - tags
  needs:
    - build-debian-buster-x86_64
  script: |
    cargo clippy -- -D warnings

build-windows-x86_64:
  stage: build
  image: $WIN64_IMAGE
  tags:
    - docker
  only:
    - main
    - merge_requests
    - tags
  script: |
    cargo build --target x86_64-pc-windows-gnu

test-windows-x86_64:
  stage: test
  image: $WIN64_IMAGE
  tags:
    - docker
  only:
    - main
    - merge_requests
    - tags
  needs:
    - build-windows-x86_64
  script: |
    cargo test --target x86_64-pc-windows-gnu --no-run

clippy-windows-x86_64:
  stage: misc
  image: $WIN64_IMAGE
  tags:
    - docker
  only:
    - main
    - merge_requests
    - tags
  needs:
    - build-windows-x86_64
  script: |
    cargo clippy --target x86_64-pc-windows-gnu -- -D warnings

.macos-common:
  before_script: |
    rustup override set $MACOS_RUST_VERSION

.build-macos-common:
  extends: .macos-common
  stage: build
  tags:
    - macos
  only:
    - main
    - merge_requests
    - tags
  script: |
    cargo build

.clippy-macos-common:
  extends: .macos-common
  stage: misc
  tags:
    - macos
  only:
    - main
    - merge_requests
    - tags
  script: |
    cargo clippy -- -D warnings

build-macos-x86_64:
  extends: .build-macos-common
  variables: *variables-macos-x86_64

clippy-macos-x86_64:
  extends: .clippy-macos-common
  variables: *variables-macos-x86_64
  needs:
    - build-macos-x86_64

build-macos-arm64:
  extends: .build-macos-common
  variables: *variables-macos-arm64

test-macos-arm64:
  extends: .macos-common
  variables: *variables-macos-arm64
  stage: test
  tags:
    - macos
  only:
    - main
    - merge_requests
    - tags
  needs:
    - build-macos-arm64
  script: |
    cargo test

clippy-macos-arm64:
  extends: .clippy-macos-common
  variables: *variables-macos-arm64
  needs:
    - build-macos-arm64
