[workspace]

resolver = "2"

members = [
    "kycom",
    "kymux",
    "kymux_client",
    "kynet",
    "kyproto",
    "kyproto-types",
]

[workspace.dependencies]
kycom = { path = "kycom" }
kymux = { path = "kymux" }
kynet = { path = "kynet" }
kyproto = { path = "kyproto" }
kyproto-types = { path = "kyproto-types" }
