[package]
name = "kyproto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytes = "1.4.0"
kynet = { version = "0.1", path = "../kynet", optional = true }
log = "0.4.20"
thiserror = "1.0.47"
tokio = { version = "1.32.0", features = ["rt", "macros", "sync"], optional = true }
wasm-bindgen = { version = "0.2.87", optional = true }
wasm-bindgen-futures = { version = "0.4.37", optional = true }

# https://doc.rust-lang.org/cargo/reference/features.html#optional-dependencies
[features]
default = []
tokio-rt = [
    "kynet/quinn",
    "dep:tokio",
]
js = [
    "kynet/webtransport-js",
    "tokio/sync",
    "dep:wasm-bindgen",
    "dep:wasm-bindgen-futures",
]
