[package]
name = "kyproto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tokio = { version = "1.32.0", optional = true }
wasm-bindgen = { version = "0.2.87", optional = true }
wasm-bindgen-futures = { version = "0.4.37", optional = true }

# https://doc.rust-lang.org/cargo/reference/features.html#optional-dependencies
[features]
default = []
tokio = ["dep:tokio"]
js = ["dep:wasm-bindgen", "dep:wasm-bindgen-futures"]
